name: run retraining and tests

on:
  pull_request:
    branches: [ main ]

jobs:
  training:
    runs-on: ubuntu-latest

    steps:
      - name: configure aws credentials (official)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      
      - name: clone dataset repo
        run: |
          git clone https://github.com/jgwiese/peanut_dataset.git
          cd peanut_dataset
          git checkout main
          pip install dvc dvc-s3
          dvc pull -v

      - name: run training container
        run: |
          docker run -v ${{ github.workspace }}/peanut_dataset/data/processed:/app/data paraficial/peanut_ml:latest

  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV

      - name: run tests with pytest
        run: |
          python -m pytest -v
